/**
 *This file was generated by AttributedClassGenerator, utility tool for libObjCAttr performance check
 */

#import <ROAD/ROADAttribute.h>
@interface AttributeClass0 : NSObject
{
id _ivar0;
id _ivar1;
id _ivar2;
id _ivar3;
id _ivar4;
id _ivar5;
id _ivar6;
id _ivar7;
id _ivar8;
id _ivar9;
}
@property (nonatomic) id property0;
@property (nonatomic) id property1;
@property (nonatomic) id property2;
@property (nonatomic) id property3;
@property (nonatomic) id property4;
@property (nonatomic) id property5;
@property (nonatomic) id property6;
@property (nonatomic) id property7;
@property (nonatomic) id property8;
@property (nonatomic) id property9;
- (void)method0;
- (void)method1;
- (void)method2;
- (void)method3;
- (void)method4;
- (void)method5;
- (void)method6;
- (void)method7;
- (void)method8;
- (void)method9;
@end
