platform :ios, '5.0'

workspace 'ROADFramework'

xcodeproj 'ROADCore/ROADCore.xcodeproj'

link_with 'ROADCore', 'ROADWebService'

target :ROADCore do
    pod 'libObjCAttr'
    xcodeproj 'ROADCore/ROADCore.xcodeproj'
end

target :ROADWebServiceTest do
    xcodeproj 'ROADWebService/ROADWebService.xcodeproj'
	pod 'Nocilla', :podspec => 'https://raw.github.com/luisobo/Nocilla/master/Nocilla.podspec'
end

post_install do |installer|
  require File.expand_path('ROADConfigurator.rb', './Pods/libObjCAttr/libObjCAttr/Resources/')
  ROADConfigurator::post_install(installer)
end
