source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '5.0'

workspace 'ROADFramework'

xcodeproj 'ROADCore/ROADCore.xcodeproj'
xcodeproj 'ROADServices/ROADServices.xcodeproj'
xcodeproj 'ROADSerialization/ROADSerialization.xcodeproj'
xcodeproj 'ROADWebService/ROADWebService.xcodeproj'

target :ROADCore do
xcodeproj 'ROADCore/ROADCore.xcodeproj'	
pod 'libObjCAttr'
end

target :ROADCoreTest do
  xcodeproj 'ROADCore/ROADCore.xcodeproj'
  pod 'libObjCAttr'
end

target :ROADServices do
  xcodeproj 'ROADServices/ROADServices.xcodeproj'	
  pod 'libObjCAttr'
end

target :ROADServicesTest do
  xcodeproj 'ROADServices/ROADServices.xcodeproj'	
  pod 'libObjCAttr'	
end

target :ROADSerialization do
  xcodeproj 'ROADSerialization/ROADSerialization.xcodeproj'
  pod 'libObjCAttr'
end

target :ROADSerializationTest do
  xcodeproj 'ROADSerialization/ROADSerialization.xcodeproj'
  pod 'libObjCAttr'
end

target :ROADWebService do
  xcodeproj 'ROADWebService/ROADWebService.xcodeproj'
  pod 'libObjCAttr'
end

target :ROADWebServiceTest do
  xcodeproj 'ROADWebService/ROADWebService.xcodeproj'
  pod 'libObjCAttr'
end

target :Utilities do
  xcodeproj 'Utilities/Utilities.xcodeproj'
end

post_install do |installer|
  require File.expand_path('ROADConfigurator.rb', './Pods/libObjCAttr/libObjCAttr/Resources/')
  ROADConfigurator::post_install(installer)
end