platform :ios, '7.0'

pod 'libObjCAttr'
pod 'HTProgressHUD', '~> 0.1'

post_install do |installer|
    require File.expand_path('ROADConfigurator.rb', './Pods/libObjCAttr/libObjCAttr/Resources/')
    ROADConfigurator::post_install(installer)
end