require File.expand_path('./', 'SparkConfigurator.rb')

platform :ios, '5.0'

pod 'SparkFramework', '~> 0.0.1'
# Add your custom pod specs here

pre_install do |installer|
  SparkConfigurator::pre_install(installer)
end

post_install do |installer|
  SparkConfigurator::post_install(installer)
end