require File.expand_path('./', 'SparkConfigurator.rb')

platform :ios, '5.0'

pod 'SparkFramework', '~> 1.1.0'

# Add your custom pod specs here

#Uncomment and set username and password for downloading binaries from private repo. Temporary. Will be removed as soon as Spark become public
#SparkConfigurator::set_github_credentials(“username”,”password”)

pre_install do |installer|
  SparkConfigurator::pre_install(installer)
end

post_install do |installer|
  SparkConfigurator::post_install(installer)
end